drop database if exists bbp;
create database bbp;
use bbp;

create table kelurahanbdg (
nama_kelurahan varchar(50) NOT NULL
)engine=innodb;

INSERT INTO `kelurahanbdg` (`nama_kelurahan`) VALUES
('Campaka'),
('Ciroyom'),
('Dunguscariang'),
('Garuda'),
('Kebonjeruk'),
('Maleber'),
('Antapani Kidul'),
('Antapani Kulon'),
('Antapani Tengah'),
('Antapani Wetan'),
('Cisaranten Endah'),
('Cisaranten Kulon'),
('Cisaranten Bina Harapan'),
('Sukamiskin'),
('Cibadak'),
('Karangannyar'),
('Karasak'),
('Nyengseret'),
('Panjunan'),
('Pelindunghewan'),
('Babakan'),
('Babakanciparay'),
('Cirangrang'),
('Margahayu Utara'),
('Margasuka'),
('Sukahaji'),
('Batununggal'),
('Mengger'),
('Wates'),
('Caringin'),
('Cibuntu'),
('Cigondewah'),
('Cigondewah Kidul'),
('Cigondewah Rahayu'),
('Cijerah'),
('Gempolsari'),
('Warungmuncang'),
('Cihapit'),
('Citarum'),
('Tamansari'),
('Binong'),
('Cibangkong'),
('Gumuruh'),
('Kacapiring'),
('Kebongedang'),
('Kebonwaru'),
('Maleer'),
('Samoja'),
('Babakan Asih'),
('Babakan Tarogong'),
('Jamika'),
('Kopo'),
('Suka Asih'),
('Cibaduyut'),
('Cibaduyut Kidul'),
('Cibaduyut Wetan'),
('Kebon Lega'),
('Mekarwangi'),
('Situsaeur'),
('Cijawura'),
('Jatisari'),
('Margasari'),
('Sekejati'),
('Cigadung'),
('Cihaurgeulis'),
('Neglasari'),
('Sukaluyu'),
('Cicadas'),
('Cikutra'),
('Padasuka'),
('Pasirlayung'),
('Sukamaju'),
('Sukapada'),
('Cipadung'),
('Cisurupan'),
('Palasari'),
('Pasirbiru'),
('Arjuna'),
('Husen Sastranegara'),
('Pajajaran'),
('Pamoyanan'),
('Pasirkaliki'),
('Sukaraja'),
('Ciumbuleuit'),
('Hegarmanah'),
('Ledeng'),
('Babakan Penghulu'),
('Cisaranten Wetan'),
('Pakemitan'),
('Sukamulya'),
('Cipaganti'),
('Dago'),
('Lebakgede'),
('Lebaksiliwangi'),
('Sadangserang'),
('Sekeloa'),
('Cimincrang'),
('Cisaranten'),
('Rancabolang'),
('Rancanumpang'),
('Babakansari'),
('Babakansurabaya'),
('Cicaheum'),
('Kebon Kangkung'),
('Kebunjayanti'),
('Sukapura'),
('Burangrang'),
('Cijagra'),
('Cikawao'),
('Lingkar Selatan'),
('Malabar'),
('Paledang'),
('Turangga'),
('Jatihandap'),
('Karangpamulang'),
('Sindangjaya'),
('Cipadung Kidul'),
('Cipadung Kulon'),
('Cipadung Wetan'),
('Mekarmulya'),
('Cipamokolan'),
('Darwati'),
('Manjahlega'),
('Mekarmulya'),
('Ancol'),
('Balonggede'),
('Ciateul'),
('Cigereleng'),
('Ciseureuh'),
('Pasirluyu'),
('Pungkur'),
('Cipedes'),
('Pasteur'),
('Sukabungah'),
('Sukagalih'),
('Sukawarna'),
('Gegerkalong'),
('Isola'),
('Sarijadi'),
('Sukarasa'),
('Babakanciamis'),
('Braga'),
('Kebonpisang'),
('Merdeka'),
('Cigending'),
('Pasanggrahan'),
('Pasirendah'),
('Pasirjati'),
('Pasirwangi'),
('Ujungberung');

create table datauser(
ktp_user varchar(20) primary key,
password varchar(255),
nama_user varchar(50),
tempat_lahir varchar(50),
tanggal_lahir date,
jk enum('Pria','Wanita'),
alamat varchar(200),
rt_user varchar(2),
rw_user varchar(2),
email varchar(100) unique
)engine=innodb;

create table daftarpengajuan(
id_pengajuan int primary key auto_increment,
ktp_user varchar(20),
status_kepemilikan enum('Pemilik','Penyewa','Pengelola','Pemakai','Sengketa'),
alamat_jalan_objek varchar(50),
alamat_nomor_objek varchar(20),
kelurahan_objek enum('Campaka','Ciroyom','Dunguscariang','Garuda','Kebonjeruk','Maleber','Antapani Kidul','Antapani Kulon','Antapani Tengah','Antapani Wetan','Cisaranten Endah','Cisaranten Kulon','Cisaranten Bina Harapan','Sukamiskin','Cibadak','Karangannyar','Karasak','Nyengseret','Panjunan','Pelindunghewan','Babakan','Babakanciparay','Cirangrang','Margahayu Utara','Margasuka','Sukahaji','Batununggal','Mengger','Wates','Carinigin','Cibuntu','Cigondewah','Cigondewah Kidul','Cigondewah Rahayu','Cijerah','Gempolsari','Warungmuncang','Cihapit','Citarum','Tamansari','Binong','Cibangkong','Gumuruh','Kacapiring','Kebongedang','Kebonwaru','Maleer','Samoja','Babakan Asih','Babakan Tarogong','Jamika','Kopo','Suka Asih','Cibaduyut','Cibaduyut Kidul','Cibaduyut Wetan','Kebon Lega','Mekarwangi','Situsaeur','Cijawura','Jatisari','Margasari','Sekejati','Cigadung','Cihaurgeulis','Neglasari','Sukaluyu','Cicadas','Cikutra','Padasuka','Pasirlayung','Sukamaju','Sukapada','Cipadung','Cisurupan','Palasari','Pasirbiru','Arjuna','Husen Sastranegara','Pajajaran','Pamoyanan','Pasirkaliki','Sukaraja','Ciumbuleuit','Hegarmanah','Ledeng','Babakan Penghulu','Cisaranten Wetan','Pakemitan','Sukamulya','Cipaganti','Dago','Lebakgede','Lebaksiliwangi','Sadangserang','Sekeloa','Cimincrang','Cisaranten','Rancabolang','Rancanumpang','Babakansari','Babakansurabaya','Cicaheum','Kebon Kangkung','Kebunjayanti','Sukapura','Burangrang','Cijagra','Cikawao','Lingkar Selatan','Malabar','Paledang','Turangga','Jatihandap','Karangpamulang','Sindangjaya','Cipadung Kidul','Cipadung Kulon','Cipadung Wetan','Mekarmulya','Cipamokolan','Darwati','Manjahlega','Mekarmulya','Ancol','Balonggede','Ciateul','Cigereleng','Ciseureuh','Pasirluyu','Pungkur','Cipedes','Pasteur','Sukabungah','Sukagalih','Sukawarna','Gegerkalong','Isola','Sarijadi','Sukarasa','Babakanciamis','Braga','Kebonpisang','Merdeka','Cigending','Pasanggrahan','Pasirendah','Pasirjati','Pasirwangi','Ujungberung'),
rw_objek varchar(2),
rt_objek varchar(2),
luas_tanah int,
jenis_tanah enum('Tanah + Bangunan','Kavling Siap Bangun','Tanah Kosong','Fasilitas Umum'),
guna_bangunan enum('Perumahan','Perkantoran Swasta','Pabrik','Toko / Apotik / Pasar / Ruko','Rumah Sakit / Klinik','Olah raga / Rekreasi','Hotel / Wisma','Bengkel / Gudang / Pertanian','Gedung Pemerintahan','Lain-lain','Bangunan Tidak Kena Pajak','Bangunan Parkir','Apartemen','Pompa Bensin','Tangki Minyak','Gedung Sekolah'),
luas_bangunan int,
jumlah_tingkat int,
tahun_dibangun year,
tahun_direnovasi year,
daya_listrik int,
kondisi enum('Sangat Baik','Baik','Sedang','Jelek'),
konstruksi enum('Baja Decarbon','Beton','Batu Bata','Kayu'),
atap enum('Beton / Genteng Glazur','Genteng Beton / Alumunium','Genteng Biasa / Sirap','Asbes','Seng'),
dinding enum('Kaca / Alumunium','Beton','Batu Bata / Conblok','Kayu','Seng'),
lantai enum('Marmer','Keramik','Teraso','Ubin PC / Papan','Semen'),
langitlangit enum('Akustik / Jati','Triplek / Asbes Bambu','Tidak Ada'),
ktp_subjek varchar(20),
pekerjaan enum('PNS','ABRI','Pensiunan','Badan','Lainnya'),
nama_subjek varchar(50),
npwp varchar(15),
alamat_jalan_subjek varchar(50),
alamat_nomor_subjek varchar(20),
kelurahan_subjek varchar(40),
rw_subjek varchar(2),
rt_subjek varchar(2),
kota varchar(30),
kode_pos varchar(7),
status enum('Disetujui','Tidak Disetujui','Belum Disetujui')
)engine=innodb;

create table datasubjek(
ktp_subjek varchar(20) primary key,
pekerjaan enum('PNS','ABRI','Pensiunan','Badan','Lainnya'),
nama_subjek varchar(50),
npwp varchar(15),
alamat_jalan_subjek varchar(50),
alamat_nomor_subjek varchar(20),
kelurahan_subjek varchar(40),
rw_subjek varchar(2),
rt_subjek varchar(2),
kota varchar(30),
kode_pos varchar(7)
)engine=innodb;

create table dataobjek(
nop varchar(18) primary key,
ktp_subjek varchar(20),
ktp_user varchar(20),
status_kepemilikan enum('Pemilik','Penyewa','Pengelola','Pemakai','Sengketa'),
alamat_jalan_objek varchar(50),
alamat_nomor_objek varchar(20),
kelurahan_objek enum('Campaka','Ciroyom','Dunguscariang','Garuda','Kebonjeruk','Maleber','Antapani Kidul','Antapani Kulon','Antapani Tengah','Antapani Wetan','Cisaranten Endah','Cisaranten Kulon','Cisaranten Bina Harapan','Sukamiskin','Cibadak','Karangannyar','Karasak','Nyengseret','Panjunan','Pelindunghewan','Babakan','Babakanciparay','Cirangrang','Margahayu Utara','Margasuka','Sukahaji','Batununggal','Mengger','Wates','Caringin','Cibuntu','Cigondewah','Cigondewah Kidul','Cigondewah Rahayu','Cijerah','Gempolsari','Warungmuncang','Cihapit','Citarum','Tamansari','Binong','Cibangkong','Gumuruh','Kacapiring','Kebongedang','Kebonwaru','Maleer','Samoja','Babakan Asih','Babakan Tarogong','Jamika','Kopo','Suka Asih','Cibaduyut','Cibaduyut Kidul','Cibaduyut Wetan','Kebon Lega','Mekarwangi','Situsaeur','Cijawura','Jatisari','Margasari','Sekejati','Cigadung','Cihaurgeulis','Neglasari','Sukaluyu','Cicadas','Cikutra','Padasuka','Pasirlayung','Sukamaju','Sukapada','Cipadung','Cisurupan','Palasari','Pasirbiru','Arjuna','Husen Sastranegara','Pajajaran','Pamoyanan','Pasirkaliki','Sukaraja','Ciumbuleuit','Hegarmanah','Ledeng','Babakan Penghulu','Cisaranten Wetan','Pakemitan','Sukamulya','Cipaganti','Dago','Lebakgede','Lebaksiliwangi','Sadangserang','Sekeloa','Cimincrang','Cisaranten','Rancabolang','Rancanumpang','Babakansari','Babakansurabaya','Cicaheum','Kebon Kangkung','Kebunjayanti','Sukapura','Burangrang','Cijagra','Cikawao','Lingkar Selatan','Malabar','Paledang','Turangga','Jatihandap','Karangpamulang','Sindangjaya','Cipadung Kidul','Cipadung Kulon','Cipadung Wetan','Mekarmulya','Cipamokolan','Darwati','Manjahlega','Mekarmulya','Ancol','Balonggede','Ciateul','Cigereleng','Ciseureuh','Pasirluyu','Pungkur','Cipedes','Pasteur','Sukabungah','Sukagalih','Sukawarna','Gegerkalong','Isola','Sarijadi','Sukarasa','Babakanciamis','Braga','Kebonpisang','Merdeka','Cigending','Pasanggrahan','Pasirendah','Pasirjati','Pasirwangi','Ujungberung'),
rw_objek varchar(2),
rt_objek varchar(2),
luas_tanah int,
jenis_tanah enum('Tanah + Bangunan','Kavling Siap Bangun','Tanah Kosong','Fasilitas Umum'),
njop_bumi int,
guna_bangunan enum('Perumahan','Perkantoran Swasta','Pabrik','Toko / Apotik / Pasar / Ruko','Rumah Sakit / Klinik','Olah raga / Rekreasi','Hotel / Wisma','Bengkel / Gudang / Pertanian','Gedung Pemerintahan','Lain-lain','Bangunan Tidak Kena Pajak','Bangunan Parkir','Apartemen','Pompa Bensin','Tangki Minyak','Gedung Sekolah'),
luas_bangunan int,
jumlah_tingkat int,
tahun_dibangun year,
tahun_direnovasi year,
daya_listrik int,
kondisi enum('Sangat Baik','Baik','Sedang','Jelek'),
konstruksi enum('Baja Decarbon','Beton','Batu Bata','Kayu'),
atap enum('Beton / Genteng Glazur','Genteng Beton / Alumunium','Genteng Biasa / Sirap','Asbes','Seng'),
dinding enum('Kaca / Alumunium','Beton','Batu Bata / Conblok','Kayu','Seng'),
lantai enum('Marmer','Keramik','Teraso','Ubin PC / Papan','Semen'),
langitlangit enum('Akustik / Jati','Triplek / Asbes Bambu','Tidak Ada'),
njop_bangunan int,
njop_dasar int,
foreign key (ktp_subjek) references datasubjek(ktp_subjek),
foreign key (ktp_user) references datauser(ktp_user)
)engine=innodb;

create table pembayaran(
id_pembayaran int primary key auto_increment,
nop varchar(18),
tahun_pajak year,
nama_bank varchar(50),
no_rekening varchar(50),
pemilik_rekening varchar(50),
tanggal_bayar date,
ktp_user varchar(20),
bukti varchar(255),
status enum("Belum Diterima, Diterima"),
foreign key (ktp_user) references datauser(ktp_user)
)engine=innodb;

create table tagihan(
nop varchar(18),
tahun_pajak year,
id_pembayaran int,
nama_subjek varchar(50),
pokok int,
denda int,
jumlah_tagihan int,
tgl_jatuh_tempo date,
jumlah_bulan int,
status_kelunasan enum('Belum Lunas','Lunas'),
primary key (nop, tahun_pajak),
foreign key (id_pembayaran) references pembayaran(id_pembayaran)
)engine=innodb;

create table dataadmin(
nip varchar(10) primary key,
password varchar(255),
nama_admin varchar(50),
email varchar(100)
)engine=innodb

INSERT INTO `dataadmin` (`nip`, `password`, `nama_admin`) VALUES
('10113050', 'faV8P3yq81o6VaeyeNnBelnh80iiiETVL0lPUAKLfpE=', 'Michael Agustian', 'michaelian12@gmail.com'),
('10113054', 'bgODWkZE3zeYqfiFIwk0LbeRJiX02nKjsxFeJs9igKk=', 'Muhammad Faizal Alfarisi', 'faizal.alfarisi@gmail.com'),
('10113070', 'fvqEq89xjN0zMoSzCTsaDSMYeEQ03D+P7p7QQ6XNnp0=', 'Samsul Arifin', 'samsul3070@gmail.com'),
('10113290', 'wPJfqAQ1jhe46RAy3h4jD3yEK1VT6i+aBVcRaI9MiPQ=', 'Jaka Pratama', 'jakapratama204@gmail.com');
